open-lessons/django-asyncio-23.04/mysite/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

open-lessons/django-asyncio-23.04/mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include


urlpatterns = [
    path("", include("homepage.urls")),
    path(
        "auth/login/",
        LoginView.as_view(template_name="admin/login.html"),
        name="login",
    ),
    path(
        "auth/logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path("admin/", admin.site.urls),
]

open-lessons/django-asyncio-23.04/mysite/homepage/models.py
from django.dispatch import receiver
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    birth_date = models.DateField(
        null=True,
        blank=True,
    )
    city = models.CharField(
        max_length=100,
        null=False,
        blank=True,
        default="",
        db_default="",
    )
    bio = models.TextField(
        null=False,
        blank=True,
        default="",
        db_default="",
    )

    class FamilyStatus(models.TextChoices):
        SINGLE = "S", "Single"
        IN_A_RELATIONSHIP = "R", "In A Relationship"
        MARRIED = "M", "Married"
        DIVORCED = "D", "Divorced"
        WIDOWED = "W", "Widowed"

    family_status = models.CharField(
        max_length=1,
        choices=FamilyStatus,
        default=None,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

open-lessons/django-asyncio-23.04/mysite/homepage/views.py
import asyncio

from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from homepage.models import Profile
from homepage.services.currencies import get_currency_exchange_rates
from homepage.services.jokes import get_joke


class HomeView(TemplateView):
    template_name = "homepage/home.html"


@login_required()
async def dashboard(request: HttpRequest) -> HttpResponse:
    user = request.user
    async with asyncio.TaskGroup() as tg:
        profile = tg.create_task(
            Profile.objects.select_related("user").aget(user=user),
        )
        currency_rates = tg.create_task(
            get_currency_exchange_rates(
                "rub",
                "JPY",
                "BTC",
            )
        )
        joke = tg.create_task(get_joke())

    context = dict(
        profile=profile.result(),
        currencies=currency_rates.result(),
        joke=joke.result(),
    )
    return render(
        request=request,
        template_name="homepage/dashboard.html",
        context=context,
    )

open-lessons/django-asyncio-23.04/mysite/homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
{% block body %}
	Base body
{% endblock %}
</body>
</html>

open-lessons/django-asyncio-23.04/mysite/homepage/templates/homepage/dashboard.html
{% extends 'homepage/base.html' %}

{% block title %}
	Dashboard
{% endblock %}

{% block body %}
  {% include 'homepage/home.html' %}
  <hr>
  <h2>User info</h2>
	<table>
    <tr>
      <td>User:</td>
      <td>{{ profile.user.username }}</td>
    </tr>
    <tr>
      <td>City:</td>
      <td>{{ profile.city }}</td>
    </tr>
    <tr>
      <td>Family Status:</td>
      <td>{{ profile.get_family_status_display }}</td>
    </tr>
    <tr>
      <td>Bio:</td>
      <td>{{ profile.bio }}</td>
    </tr>
  </table>

  <hr/>
  <h2>Currency rates</h2>
  <table>
    <tr>
      <th>Currency</th>
      <th>Rate</th>
    </tr>
    {% for currency, rate in currencies.items %}
      <tr>
        <td><code>{{ currency|upper }}</code></td>
        <td>{{ rate }}</td>
      </tr>
    {% endfor %}
  </table>
  <hr>
  <h2>New joke:</h2>
  <blockquote>
    {{ joke|linebreaksbr }}
  </blockquote>
{% endblock %}

open-lessons/django-asyncio-23.04/mysite/homepage/templates/homepage/home.html
{% extends 'homepage/base.html' %}

{% block title %}
	Home
{% endblock %}

{% block body %}
	{% if request.user.is_anonymous %}
    <a href="{% url 'login' %}?next=/">Login</a>
  {% else %}
    <div>
      Hello, {{ request.user.username }}
    </div>
    <div>
      <a href="{% url 'homepage:dashboard' %}">Dashboard</a>
    </div>
    <br>
    <div>
      <form action="{% url 'logout' %}?next=/" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
      </form>
    </div>
	{% endif %}
{% endblock %}