lessons/lesson.23/shop_project/demo_api/urls.py
from django.urls import path

from .views import (
    PingApiView,
)

app_name = "demo_api"

urlpatterns = [
    path("ping/", PingApiView.as_view(), name="ping"),
]

lessons/lesson.23/shop_project/shop_app/urls.py
from django.urls import path

from .views import (
    IndexView,
    CategoriesListView,
    CategoriesMinListView,
    CategoryDetailView,
    ProductsListView,
    ProductDetailView,
    CategoryCreateView,
    ProductCreateView,
    CategoryDeleteView,
    ProductDeleteView,
    CategoryUpdateView,
    ProductUpdateView,
    OrdersListView,
    task_status,
)

app_name = "shop_app"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    # path("", index_view, name="index"),
    path("categories-min/", CategoriesMinListView.as_view(), name="categories-min"),
    path("categories/", CategoriesListView.as_view(), name="categories"),
    path("categories/add/", CategoryCreateView.as_view(), name="category-add"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),
    path(
        "categories/<int:pk>/confirm-delete/",
        CategoryDeleteView.as_view(),
        name="category-confirm-delete",
    ),
    path(
        "categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category-edit"
    ),
    path("products/", ProductsListView.as_view(), name="products"),
    path("products/add/", ProductCreateView.as_view(), name="product-add"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product"),
    path(
        "products/<int:pk>/confirm-delete/",
        ProductDeleteView.as_view(),
        name="product-confirm-delete",
    ),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-edit"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("task-status/", task_status, name="task-status"),
]

lessons/lesson.23/shop_project/shop_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("shop/", include("shop_app.urls")),
    path("api/shop/", include("shop_app.api_urls")),
    # path("api/shop/", include("shop_app.api_urls")),
    path("api/demo/", include("demo_api.urls")),
]

if not settings.TESTING:
    urlpatterns.extend(
        debug_toolbar_urls(),
    )

lessons/lesson.23/shop_project/shop_app/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

UserModel = get_user_model()


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["pk"]

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=False, blank=True)

    @property
    def id_hash(self):
        return hash(self.pk)

    @property
    def name_hash(self):
        return hash(self.name)

    def get_absolute_url(self):
        return reverse("shop_app:category", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        ordering = ["pk"]

    title = models.CharField(max_length=100, unique=False)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    archived = models.BooleanField(default=False)
    categories = models.ManyToManyField(
        to=Category,
        related_name="products",
        # unique=True,
    )

    def get_absolute_url(self):
        return reverse("shop_app:product", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class Order(models.Model):
    class Meta:
        ordering = ["pk"]

    class Status(models.TextChoices):
        NEW = "NEW", "New"
        PENDING = "PENDING", "Pending"
        SHIPPED = "SHIPPED", "Shipped"
        DELIVERED = "DELIVERED", "Delivered"
        CANCELLED = "CANCELLED", "Cancelled"

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.PROTECT,
        related_name="orders",
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.NEW,
    )
    address = models.TextField(null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    products = models.ManyToManyField(
        to=Product,
        through="OrderProduct",
        related_name="orders",
    )

    def __str__(self):
        return f"{self.user} - {self.status} - {self.address}"


class OrderProduct(models.Model):
    class Meta:
        ordering = ["pk"]

    product = models.ForeignKey(
        to=Product,
        on_delete=models.PROTECT,
        related_name="order_products",
    )
    order = models.ForeignKey(
        to=Order,
        on_delete=models.PROTECT,
        related_name="order_products",
    )
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"OrderProduct {self.pk} {self.product} {self.quantity} {self.price}"


#
# class User:
#
#     def __init__(self, username: str):
#         self.username = username
#
#
# john = User(username="john")
#
# print("!!!!")
# print(type(john))
# print(type(User))
#
# """
# Джон - экземпляр класса User
# Джон типа (of type) User
#
# User of type ...? (metaclass)
# """

lessons/lesson.23/shop_project/shop_app/forms.py
from django import forms

from shop_app.models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "name",
            "description",
        ]
        widgets = {
            "description": forms.Textarea(attrs={"cols": 40, "rows": 5}),
        }
        labels = {
            "name": "Category name",
        }
        help_texts = {
            "name": "Used for product categories (m2m)",
        }
    # name = forms.CharField(label="Category name", max_length=100)
    # description = forms.CharField(widget=forms.Textarea)

lessons/lesson.23/shop_project/shop_app/views.py
"""
Create
Read
Update
Delete
"""

from celery.result import AsyncResult
from django.http import (
    HttpResponseRedirect,
    HttpRequest,
    HttpResponse,
    # JsonResponse,
)
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from shop_app.models import Category, Product, Order
from shop_app.forms import CategoryForm


# def get_api_data(request):
#     return JsonResponse({})


class IndexView(TemplateView):
    template_name = "shop_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['some_data'] = 'Some text'
        return context


class CategoriesMinListView(TemplateView):
    template_name = "shop_app/categories.html"

    extra_context = {
        "pi": 3.1415,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            categories=Category.objects.all(),
        )
        return context


class CategoriesListView(ListView):
    model = Category
    # queryset = Category.objects.order_by("name").all()
    template_name = "shop_app/categories.html"
    context_object_name = "categories"


class CategoryDetailView(DetailView):
    model = Category


class CategoryCreateView(CreateView):
    template_name = "shop_app/category-create.html"
    model = Category
    form_class = CategoryForm
    # success_url = reverse_lazy("shop_app:categories")

    # success_url = reverse_lazy("shop_app:categories")

    # def get_success_url(self):
    #     return reverse("shop_app:category", kwargs={"pk": self.object.pk})
    #


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy("shop_app:categories")


class CategoryUpdateView(UpdateView):
    template_name = "shop_app/category-update.html"
    model = Category
    form_class = CategoryForm

    # def get_success_url(self):
    #     return reverse("shop_app:category", kwargs={"pk": self.object.pk})


class ProductsListView(ListView):
    # model = Product
    queryset = (
        Product.objects.filter(archived=False).prefetch_related("categories").all()
    )


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    fields = [
        "title",
        "description",
        "price",
        "categories",
    ]

    # success_url = reverse_lazy("shop_app:products")
    # def get_success_url(self):
    #     return reverse("shop_app:product", kwargs={"pk": self.object.pk})

    # def form_valid(self, form):
    #     self.object.send_created_email()
    #     return super().form_valid(form)

    # def form_valid(self, form):
    #     self.object.send_email.delay()
    #     return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shop_app:products")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Product
    fields = [
        "title",
        "description",
        "price",
        "categories",
    ]


class OrdersListView(ListView):
    queryset = (
        Order.objects
        # .prefetch_related("order_products")
        # .prefetch_related("order_products__product")
        .prefetch_related("order_products__product__categories")
        .select_related("user")
        .all()
    )


def task_status(request: HttpRequest) -> HttpResponse:
    context = {}
    task_id = request.GET.get("task_id")
    result = AsyncResult(task_id)
    is_ready = result.ready()
    status = result.status
    task_result = result.result
    context.update(
        task_id=task_id,
        is_ready=is_ready,
        status=status,
        result=task_result,
    )
    return render(
        request=request,
        template_name="shop_app/task_status.html",
        context=context,
    )

lessons/lesson.23/shop_project/shop_app/templates/shop_app/base.html
{% extends 'base.html' %}

{% block footer %}
	<div>
  Products Shop App
  </div>
  
  {{ block.super }}
{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/categories.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Categories list
{% endblock %}

{% block body %}
  <h1>Categories</h1>

  <ul>
    {% for category in categories %}
      <li><a href="{% url 'shop_app:category' pk=category.pk %}"
      >{{ category.name }}</a></li>
    {% endfor %}
  </ul>

  {% if pi is not None %}
    <div>
      PI: {{ pi }}
    </div>
  {% endif %}

  <div>
    <a href="{% url 'shop_app:category-add' %}">Add a new category</a>
  </div>
  {% include 'shop_app/components/back-to-shop-index.html' %}
  

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/category-create.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Add Category
{% endblock %}

{% block body %}
  <h1>Create Category</h1>

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add">
  </form>
  {% include 'shop_app/components/back-to-categories-list.html' %}

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/category-update.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Update Category
{% endblock %}

{% block body %}
  <h1>Update Category {{ category.pk }}</h1>

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update">
  </form>

  <div>
    <a href="{% url 'shop_app:category' pk=category.pk %}">Back to category details</a>
  </div>

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/category_confirm_delete.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Delete Category
{% endblock %}

{% block body %}
  <h1>Delete Category</h1>
  
  <p>
    Are you sure you want to delete category <b>{{ category.name }}</b>?
  </p>

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Delete">
  </form>
  
  <div>
    <a href="{% url 'shop_app:category' pk=category.pk %}">Back to category details</a>
  </div>

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/category_detail.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Category {{ category.name }}
{% endblock %}

{% block body %}
  <h1>Category {{ category.name }} details</h1>
  <p>
    <strong>Description:</strong>
    {{ category.description }}
  </p>
  
  <div>
    <a href="{% url 'shop_app:category-edit' pk=category.pk %}"
    >Edit category</a>
  </div>
  
  <div>
    <a href="{% url 'shop_app:category-confirm-delete' pk=category.pk %}"
    >Delete category</a>
  </div>
  {% include 'shop_app/components/back-to-categories-list.html' %}
{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/index.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Products Index
{% endblock %}

{% block body %}
  <h1>Products list</h1>

  <ul>
    <li>
      <a href="{% url 'shop_app:categories' %}">Categories</a>
    </li>
    <li>
      <a href="{% url 'shop_app:products' %}">Products</a>
    </li>
    <li>
      <a href="{% url 'shop_app:orders' %}">Orders</a>
    </li>
    <li>
      <a href="{% url 'shop_app:task-status' %}">Task Status</a>
    </li>
  </ul>

  {{some_data}}

  <div>
    <a href="{% url 'index' %}">Back to index</a>
  </div>
{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/order_list.html
{% extends 'shop_app/index.html' %}

{% block title %}
  All Orders list
{% endblock %}

{% block body %}
  <h1>Orders</h1>
  {% for order in order_list %}
    <div>
      <p>Order #{{ order.pk }} from {{ order.created_at }}</p>
      <p><strong>Ordered by:</strong> {{ order.user }}</p>
      <ul>
        {% for order_product in order.order_products.all %}
          <li>{{ order_product.product.title }} - ₽{{ order_product.price }} × {{ order_product.quantity }}</li>
          <ul>
            {% for category in order_product.product.categories.all %}
              <li>{{ category.name }}</li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
    </div>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}

  {% include 'shop_app/components/back-to-shop-index.html' %}

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/product_confirm_delete.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Delete Product
{% endblock %}

{% block body %}
  <h1>Delete Product</h1>
  
  <p>
    Are you sure you want to delete product <b>{{ category.title }}</b> of price {{ product.price }}?
  </p>

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Delete">
  </form>
  
  <div>
    <a href="{% url 'shop_app:product' pk=product.pk %}">Back to product details</a>
  </div>

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/product_detail.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Product '{{ product.title }}' details
{% endblock %}

{% block body %}
  <h1>Product <b>{{ product.title }}</b> details</h1>
  <div>
    
    <p><strong>Price:</strong> {{ product.price }}</p>
    <p><strong>Description:</strong> {{ product.description }}</p>
  </div>
  
  <div>
  Categories:
  <ul>
    {% for category in product.categories.all %}
    	<li><a href="{% url 'shop_app:category' pk=category.pk %}"
      >{{ category.name }}</a></li>
    {% endfor %}
    
  </ul>
  </div>
  
  <div>
    <a href="{% url 'shop_app:product-edit' pk=product.pk %}"
    >Edit product</a>
  </div>
  
  <div>
    <a href="{% url 'shop_app:product-confirm-delete' pk=product.pk %}"
    >Delete product</a>
  </div>
  
  {% include 'shop_app/components/back-to-products-list.html' %}
{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/product_form.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Add Product
{% endblock %}

{% block body %}
  <h1>Create Product</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
  </form>
  {% include 'shop_app/components/back-to-products-list.html' %}

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/product_list.html
{% extends 'shop_app/index.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products</h1>
  <ul>
    {% for product in product_list %}
      <li>
        <a href="{% url 'shop_app:product' pk=product.pk %}"
      >{{ product.title }}</a> - ₽{{ product.price }}
        <ul>
          {% for category in product.categories.all %}
          	<li>{{ category.name }}</li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>

  <div>
    <a href="{% url 'shop_app:product-add' %}">Create a new product</a>
  </div>
  {% include 'shop_app/components/back-to-shop-index.html' %}
  
{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/product_update_form.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Update Product
{% endblock %}

{% block body %}
  <h1>Update Product {{ product.pk }}</h1>

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update">
  </form>

  <div>
    <a href="{% url 'shop_app:product' pk=product.pk %}">Back to product details</a>
  </div>

{% endblock %}

lessons/lesson.23/shop_project/shop_app/templates/shop_app/task_status.html
{% extends 'shop_app/base.html' %}

{% block title %}
	Task status
{% endblock %}

{% block body %}
	<h1>Task <code>{{ task_id }}</code> status</h1>
  <h2>is ready: {{ is_ready }}</h2>
  <h2>Status: {{ status }}</h2>
  <h2>Result: {{ result }}</h2>

  <hr>
  <form>
    <label for="t-id">Task id:</label>
    <input type="text" name="task_id" id="t-id" 
           value="{% firstof task_id '' %}">
    <button type="submit">Get status</button>
  </form>
{% endblock %}