open-lessons/django-intro-23.01.2025/suren_blog/blog/urls.py
from django.urls import path, include

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("add/", views.PostCreateView.as_view(), name="add"),
]

open-lessons/django-intro-23.01.2025/suren_blog/suren_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
]

open-lessons/django-intro-23.01.2025/suren_blog/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):

    class Meta:
        ordering = ["-published"]
        indexes = [
            models.Index(fields=["-published"]),
        ]

    class Status(models.TextChoices):
        DRAFT = "DR", "Draft"
        PUBLISHED = "PB", "Published"

    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT,
        db_index=True,
    )
    title = models.CharField(max_length=200)
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts",
    )
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

open-lessons/django-intro-23.01.2025/suren_blog/blog/views.py
"""
Create
Read
Update
Delete
"""

from django.contrib.auth.mixins import LoginRequiredMixin

# from django.db import transaction
# from django.shortcuts import render
# from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView

from .models import Post


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    # model = Post
    queryset = Post.objects.select_related("author")


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = [
        "title",
        "body",
        # "author",
    ]

    # @transaction.atomic
    def form_valid(self, form):
        form.instance.author = self.request.user
        # self.request.user.profile.last_publication = timezone.now()
        return super().form_valid(form)

open-lessons/django-intro-23.01.2025/suren_blog/blog/templates/blog/base.html
{% extends 'base.html' %}

open-lessons/django-intro-23.01.2025/suren_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block body %}
	<h1>{{ post.title }}</h1>
  <h6>published {{ post.published|date:"d M Y" }} at {{ post.published|date:"H:i" }}
    by {{ post.author }}
  </h6>

  <p>
    {{ post.body }}
  </p>

  <br>
  <a href="{% url 'blog:index' %}">back to Blog posts list</a>
{% endblock %}

open-lessons/django-intro-23.01.2025/suren_blog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block title %}
	Add a new post
{% endblock %}

{% block body %}
	<h2>Create a new post:</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Create</button></p>
  </form>
{% endblock %}

open-lessons/django-intro-23.01.2025/suren_blog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}
  Posts list
{% endblock %}

{% block body %}
  <ul>
    {% for post in post_list %}
      <li><a href="{% url 'blog:detail' post.pk %}"
      ><b>{{ post.title }}</b></a>
        {{ post.published|date:"d M Y" }} at {{ post.published|date:"H:i" }}</li>
    {% endfor %}
  </ul>

  <br>
  <p>
  <a href="{% url 'blog:add' %}">Add a new post</a>
  </p>
{% endblock %}