open-lessons/django-cbv-17.06/task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("tasks/", include("tasks.urls")),
    path("admin/", admin.site.urls),
]

open-lessons/django-cbv-17.06/task_manager/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.TasksIndexView.as_view(), name="index"),
    path("all/", views.AllTasksListView.as_view(), name="all"),
    path("done/", views.DoneTasksListView.as_view(), name="done"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="detail"),
]

open-lessons/django-cbv-17.06/task_manager/tasks/models.py
from django.db import models
from django.urls import reverse


class Task(models.Model):

    class Meta:
        ordering = "id",

    title = models.CharField(max_length=255)
    description = models.TextField(null=False, blank=True)
    done = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("tasks:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

open-lessons/django-cbv-17.06/task_manager/tasks/views.py
from random import randint

from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
)

from tasks.models import Task

ANSWER = 42


class TasksIndexView(TemplateView):
    template_name = "tasks/index.html"

    extra_context = {
        "answer": ANSWER,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            number=randint(1, 100),
        )
        return context


class AllTasksListView(ListView):
    model = Task


class DoneTasksListView(ListView):
    extra_context = {
        "title": "Done tasks",
    }
    queryset = Task.objects.filter(done=True).all()


class TaskDetailView(DetailView):
    model = Task


class TaskCreateView(CreateView):
    model = Task
    template_name_suffix = "_create_form"
    fields = "title", "description"

    # success_url = reverse_lazy("tasks:all")

open-lessons/django-cbv-17.06/task_manager/tasks/templates/tasks/index.html
{% extends 'base.html' %}

{% block title %}
  Tasks Index
{% endblock %}

{% block body %}
  <h1>Hello Tasks Index!!!</h1>

  <div>
    <p><strong>Answer:</strong> {{ answer }}</p>
    <p><strong>Number:</strong> {{ number }}</p>
  </div>

  <ul>
    <li><a href="{% url 'tasks:all' %}">All tasks</a></li>
    <li><a href="{% url 'tasks:done' %}">Done tasks</a></li>
  </ul>

  <br>
  <div><a href="{% url 'index' %}">Back to index</a></div>

{% endblock %}

open-lessons/django-cbv-17.06/task_manager/tasks/templates/tasks/task_create_form.html
{% extends 'base.html' %}

{% block title %}
  Create task
{% endblock %}

{% block body %}

  <h1>Create task</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
  </form>

  <div><a href="{% url 'tasks:index' %}">Back to Tasks index</a></div>

{% endblock %}

open-lessons/django-cbv-17.06/task_manager/tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block title %}
  Task {{ task.title }}
{% endblock %}

{% block body %}

  <h1>Tasks #{{ task.id }}</h1>

  <div>
    <p><strong>{{ task.title }}</strong></p>
    <p>
      <strong>Description</strong>
      <br>
      {{ task.description }}
    </p>
  </div>

  <div><a href="{% url 'tasks:all' %}">Back to Tasks list</a></div>

{% endblock %}

open-lessons/django-cbv-17.06/task_manager/tasks/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block title %}
  {% firstof title 'All tasks' %}
{% endblock %}

{% block body %}

  <h1>Tasks:</h1>
  {% if task_list %}
    <ul>
      {% for task in task_list %}
        <li><a href="{% url 'tasks:detail' pk=task.pk %}">{{ task }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No tasks yet. Create a new one.</h2>
  {% endif %}
  
  <div>
    <a href="{% url 'tasks:create' %}">Create task</a>
  </div>
  <div><a href="{% url 'tasks:index' %}">Back to Tasks index</a></div>

{% endblock %}